ci: add pull request commenter
brown-ccv/ccv-website-hugo pull request #156
Opened 2019-12-13 21:24 UTC by mcmcgrath13

### Pull Request
---

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [x] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [x] If changes affect development, was the README updated?

##### If PR to `release`
- [ ] Development site (https://brown-ccv.github.io/ccv-website) was checked and looks as expected.

##### If PR to `master`
- [ ] Staging site (https://datasci.brown.edu) was checked and looks as expected.

2019-12-16 15:07 UTC, fernandogelin commented
@mcmcgrath13 we probably want one checkbox per reviewer so they can actually use it..

2019-12-16 15:09 UTC, mcmcgrath13 commented
@fernandogelin I'm not sure what you mean - what do you envision?

2019-12-16 15:09 UTC, fernandogelin commented
- [ ] [ ] [ ] item one

2019-12-16 15:10 UTC, fernandogelin commented
never mind, it doesn't work

2019-12-16 15:13 UTC, mcmcgrath13 commented
Each reviewer has their own comment at this point - it could be approached differently (within the abilities of md).  What do you think would be best?

2019-12-17 18:54 UTC, fernandogelin approved these changes

2019-12-17 19:43 UTC, fernandogelin requested changes

2019-12-17 19:43 UTC, fernandogelin commented on .github/CODE_REVIEW/tech.md
> +Make sure the updates follow the contribution guidelines and the code is clear.  Some of the things you should check:
can you add a link to the readme and maybe to the contribution section?

2019-12-17 19:43 UTC, fernandogelin commented on .github/CODE_REVIEW/tech.md
> +- [ ] All commits use conventional style
add link to https://www.conventionalcommits.org/en/v1.0.0/
- [ ] All commits use [conventional style](https://www.conventionalcommits.org/en/v1.0.0/)

2019-12-17 19:43 UTC, fernandogelin commented on .github/CODE_REVIEW/tech.md
> +- [ ] Website builds
not sure if this is necessary. When users commit using `npm run commit` it will try to build the website and will only allow the commit if the website builds.

2019-12-17 19:43 UTC, fernandogelin commented on .github/CODE_REVIEW/tech.md
> +- [ ] Website builds
maybe just add if PR to `production` check staging site (with link)

2019-12-17 19:45 UTC, mirestrepo approved these changes
Looks great!

2019-12-17 19:45 UTC, fernandogelin approved these changes

2019-12-17 19:48 UTC, mcmcgrath13 commented on .github/CODE_REVIEW/tech.md
> +- [ ] Website builds
I don't trust people to run npm run commit and by people I mean me.

2019-12-17 19:49 UTC, mcmcgrath13 commented on .github/CODE_REVIEW/tech.md
> +- [ ] Website builds
These comments don't exist for PR's to production, but there could be anew checklist/workflow that does

2019-12-17 19:50 UTC, fernandogelin approved these changes

2019-12-17 19:51 UTC, fernandogelin commented on .github/CODE_REVIEW/tech.md
> +- [ ] Website builds
😈

2019-12-17 20:01 UTC, mcmcgrath13 commented
@fernandogelin are you ready to merge?

2019-12-17 20:09 UTC, fernandogelin approved these changes

2019-12-17 20:25 UTC, merged