feat: separate facilities section
brown-ccv/ccv-website-hugo pull request #207
Opened 2020-03-06 16:11 UTC by paulstey

### Pull Request
This PR implements the separate facilities statement that fixes Issue 200. 

#### PR Summary
@mcmcgrath13 implemented a new stand-alone section for the Facilities statement. I also made a couple of corrections (e.g., adding hyphens where appropriate) and updated the node and core count.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [ ] Local site looks as expected after changes.
- [ ] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2020-03-06 16:29 UTC, azsom approved these changes
looks good to me

Andras

2020-03-06 16:52 UTC, mttunca approved these changes

2020-03-09 15:02 UTC, fernandogelin requested changes
`config.yml` seems outdated, the address is not showing.
I'm not sure I agree with having a whole page for Facilities where all you have are instructions on how to write about CCV's facilities in a grant, and repeating How To Cite CCV.
Maybe we need a section under about, say: CCV in publications and grants with subsections: using CCV facilities, citing CCV.
When someone sees 'Facilities' in the menu they expect to see all the facilities, not just a paragraph on how to write about CCV facilities in a grant. I would expect to see something like we have under Services, but with the facilities.

2020-03-09 20:20 UTC, paulstey commented
@fernandogelin : I believe the thinking is that we will add to the Facilities section (e.g., graphics lab, high-speed research network connections, Isilon, etc.). We would also add some meat on the current version of the cluster description. Does that seem reasonable? And I like your idea about "_Citing CCV_" and "_Using CCV Facilities_".

2020-03-16 13:46 UTC, fernandogelin approved these changes

2020-03-16 13:46 UTC, merged