Feat rates table
brown-ccv/ccv-website-hugo pull request #216
Opened 2020-03-24 03:02 UTC by singhsaluja

### Pull Request
---

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [ ] Local site looks as expected after changes.
- [ ] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2020-03-24 03:04 UTC, singhsaluja commented
@fernandogelin Is there a way to left-align the content in rates.md it's centered right now which looks a little off.

2020-03-24 12:06 UTC, fernandogelin commented
@singhsaluja what part are you talking about? Everything looks left aligned to me. Also, can you resolve conflicts and update the branch?

2020-03-24 12:08 UTC, fernandogelin requested changes

2020-03-24 12:08 UTC, fernandogelin commented on themes/gb-theme/layouts/shortcodes/rates.html
> +<table style="width: 120%; margin-left:-10%;">
you can play around with width and left margin for the table by changing the style here, not sure if that's what you meant by left align.

2020-03-24 12:08 UTC, fernandogelin commented on themes/gb-theme/layouts/shortcodes/rates.html
> +      <td>$400</td>
it's missing a data point here.

2020-03-24 15:04 UTC, singhsaluja reviewed
@fernandogelin The table looks fine - no align changes required there. But content in markdown is centered. Is there an attribute to set content to be left-aligned?

2020-03-24 15:04 UTC, singhsaluja commented on themes/gb-theme/layouts/shortcodes/rates.html
> +      <td>$400</td>
This is fixed now. Thanks for reminding me.

2020-03-25 14:16 UTC, mttunca approved these changes

2020-03-25 14:17 UTC, paulstey approved these changes

2020-03-25 14:19 UTC, merged