feat: 🎸 reaorg consulting section, add getting help section
brown-ccv/ccv-website-hugo pull request #221
Opened 2020-03-30 14:42 UTC by fernandogelin

Closes: re #130, re #151

### Pull Request
---

#### PR Summary
Reorganize the Consulting section. Add Getting Help Section. Add Slack link in the footer.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [x] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2020-03-30 15:16 UTC, mcmcgrath13 requested changes

2020-03-30 15:16 UTC, mcmcgrath13 commented on content/english/services/consulting/advanced-research-computing.md
> +## High-Preformance Computing
typo - `Performance`

2020-03-30 15:16 UTC, mcmcgrath13 commented on content/english/services/consulting/advanced-research-computing.md
> +CCV's team of computational scientists and software engineers help researchers get the most out of Brown's high-performance computing (HPC) resources. They provide a range of services, including:
no one has the title of `computational scientist` - should this be `data scientist`?

2020-03-30 15:16 UTC, mcmcgrath13 commented on content/english/services/consulting/advanced-research-computing.md
> +lead: Support for researchers seeking help with statistical modeling, machine learning, data mining, data visualization, computational biology, high-performance computing, and software engineering.
the other leads don't have a period - looks out of place

2020-03-30 15:16 UTC, mcmcgrath13 commented on content/english/services/consulting/advanced-research-computing.md
> + - Expertise with graphics software and packages
be consistent in use of `-` or `*` for bulleted lists

2020-03-30 15:16 UTC, mcmcgrath13 commented on content/english/services/consulting/advanced-research-computing.md
> +The Computational Biology Core provides assistance in experimental design and data processing pipelines for high-throughput datasets generated in individual projects, particularly for DNA/RNA sequenc
Avoid use of `Our` - `CBC's` instead.

2020-03-30 15:16 UTC, mcmcgrath13 commented on content/english/services/consulting/advanced-research-computing.md
> +## High-Preformance Computing
these new sections seem pretty repetitive with `our teams` - what is the intended difference?

2020-03-30 15:16 UTC, mcmcgrath13 commented on content/english/services/consulting/deskpro.md
> +title: "CCV Helpdesk"
all of the `getting help` cards `tagDescriptions` use full sentences, whereas the other sections cards do not - make consistent

2020-03-30 15:16 UTC, mcmcgrath13 commented on content/english/services/consulting/discourse.md
>  A shared community resource, providing a discussion forum to share skills, knowledge and interests through ongoing conversation.
This seems like it should be the lead, and the lead should be this.

2020-03-30 15:16 UTC, mcmcgrath13 commented on content/english/services/consulting/office_hours.md
> +tagDescription: CCV Share is a collection of Slack channels where CCV staff and the community will be available to discuss your questions!
this `tagDescription` doesn't match the title/lead

2020-03-30 15:18 UTC, fernandogelin commented on content/english/services/consulting/advanced-research-computing.md
> +lead: Support for researchers seeking help with statistical modeling, machine learning, data mining, data visualization, computational biology, high-performance computing, and software engineering.
@mcmcgrath13 do you have a suggestion?

2020-03-30 15:19 UTC, fernandogelin commented on content/english/services/consulting/advanced-research-computing.md
> +## High-Preformance Computing
@paulstey what do you think?

2020-03-30 15:19 UTC, fernandogelin commented on content/english/services/consulting/deskpro.md
> +title: "CCV Helpdesk"
this doesn't matter for getting help. That can be removed.

2020-03-30 15:20 UTC, mcmcgrath13 commented on content/english/services/consulting/advanced-research-computing.md
> +lead: Support for researchers seeking help with statistical modeling, machine learning, data mining, data visualization, computational biology, high-performance computing, and software engineering.
Remove the period

2020-03-30 15:22 UTC, fernandogelin commented on content/english/services/consulting/advanced-research-computing.md
> +CCV's team of computational scientists and software engineers help researchers get the most out of Brown's high-performance computing (HPC) resources. They provide a range of services, including:
research software engineers I would say

2020-03-30 15:22 UTC, mcmcgrath13 commented on content/english/services/consulting/deskpro.md
> +title: "CCV Helpdesk"
is `tagDescription` not what's used in the cards in the services page? whatever that part is is what's out of stylistic sync with the other carsd.

2020-03-30 15:27 UTC, fernandogelin commented on content/english/services/consulting/advanced-research-computing.md
> +lead: Support for researchers seeking help with statistical modeling, machine learning, data mining, data visualization, computational biology, high-performance computing, and software engineering.
oh nm I misread..

2020-03-30 15:33 UTC, fernandogelin commented on content/english/services/consulting/deskpro.md
> +title: "CCV Helpdesk"
this should be a separate issue. It looks like there's a duplication of content, the tags are only being used in twitter/og tags.

2020-03-30 21:21 UTC, paulstey commented on content/english/services/consulting/advanced-research-computing.md
> +## High-Preformance Computing
I think there certainly is overlap, but certainly some differences. If it helps, I'd be more than happy to write a more general introductory section, and then integrate all the existing content in to the description of the teams. What do you all think?

@mcmcgrath13 @fernandogelin @mirestrepo

2020-03-30 21:24 UTC, fernandogelin commented on content/english/services/consulting/advanced-research-computing.md
> +## High-Preformance Computing
that would be great @paulstey

2020-03-30 21:33 UTC, mttunca approved these changes

2020-03-31 14:25 UTC, paulstey commented on content/english/services/consulting/advanced-research-computing.md
> +## High-Preformance Computing
Okay, great! I'll take this, @fernandogelin  and @mcmcgrath13!!

2020-04-09 17:09 UTC, fernandogelin commented on content/english/services/consulting/advanced-research-computing.md
> +## High-Preformance Computing
@paulstey did you have time to work on this?

2020-04-09 17:11 UTC, mcmcgrath13 commented on content/english/services/consulting/advanced-research-computing.md
on line 17 it should say `The breadth...` instead of `breath`

2020-04-29 18:12 UTC, merged