feat: 🎸 add calendar
brown-ccv/ccv-website-hugo pull request #247
Opened 2020-04-29 18:13 UTC by TiffL

### Pull Request
---

#### PR Summary
Add new calendar to replace google calendar on homepage.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [x] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2020-04-29 18:16 UTC, fernandogelin approved these changes

2020-04-29 18:26 UTC, hkershaw-brown commented
Hello, it looks like events are only being grabbed for the current month.  e.g. for this week on 

https://brown-ccv.github.io/ccv-calendar/

there is no office hours event on Friday.  I am guessing this is because Friday is May 1st.

2020-04-29 18:29 UTC, hkershaw-brown commented
The more info linking to events.brown.edu is really nice.

2020-04-29 18:35 UTC, mcmcgrath13 commented
This is awesome @TiffL !!!

A few nit picks/bugs:

1. Right now, friday is shown as 4/1 in week view, but it should be 5/1, also per @hkershaw-brown we need to grab the events there.
2. Can we move the see full calendar link closer to the calendar? I didn't notice it and then was looking for a next week button and couldn't find that either.

2020-04-29 18:36 UTC, mcmcgrath13 requested changes

2020-04-29 18:36 UTC, mcmcgrath13 commented on themes/gb-theme/layouts/partials/blocks/events.html
> +    <!--<iframe src="https://calendar.google.com/calendar/b/1/embed?height=400&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;src=Y2N2LWJvdEBicm93bi5lZHU&amp;color=%2322AA99&amp;show
delete this comment

2020-04-30 14:25 UTC, TiffL commented
Hi all, thanks! I've made the changes

2020-04-30 14:34 UTC, mcmcgrath13 approved these changes
This is awesome! 🚀

2020-04-30 14:41 UTC, paulstey approved these changes
This looks absolutely phenomenal!! Thank you!!

2020-05-04 15:52 UTC, paulstey commented
@fernandogelin & @mcmcgrath13: Can we go ahead and merge this guy?

2020-05-04 16:05 UTC, mcmcgrath13 commented
@paulstey it's still in the waiting period, otherwise yes!

2020-05-06 18:27 UTC, merged