Add Globus Service Content
brown-ccv/ccv-website-hugo pull request #250
Opened 2020-05-05 19:19 UTC by Kilatsat

### Pull Request
---

#### PR Summary
Creates the Service element and Description pages for Globus

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [x] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2020-05-05 19:38 UTC, fernandogelin requested changes

2020-05-05 19:38 UTC, fernandogelin commented on content/english/services/infrastructure/globus.md
> +
add: `docs_link: globus`, this will create a link to the docs in the globus card, similar to oscar, stronghold and jupyterhub cards

2020-05-11 13:48 UTC, fernandogelin approved these changes

2020-05-11 14:00 UTC, ashokrags commented
"Endpoints are like collections pointing to subscribers specific datasets like his/her Google drive, research share or a folder on a computer."  -- Probably need to be rephrased to something like "Endpoints are data locations pointing to subscribers specific datasets like his/her Google drive, research share or a folder on a computer.

2020-05-11 14:06 UTC, broarr commented on content/english/services/infrastructure/globus.md
> +Globus is a secure, reliable research data management service. With Globus, subscribers can move, share, & discover data via a single interface – whether your files live on a supercomputer, lab clust
>Endpoints are like collections pointing to subscribers specific datasets like his/her Google drive, research share or a folder on a computer.

Can we use more gender neutral language here? Maybe:

> Endpoints are like collections pointing to subscribers specific datasets like a researcher's personal Google drive, research share or a folder on a computer.

2020-05-11 14:10 UTC, fernandogelin commented on content/english/services/infrastructure/globus.md
> +Globus is a secure, reliable research data management service. With Globus, subscribers can move, share, & discover data via a single interface – whether your files live on a supercomputer, lab clust
I was thinking the same thing! @Kilatsat

2020-05-11 14:12 UTC, ashokrags commented on content/english/services/infrastructure/globus.md
> +Globus is a secure, reliable research data management service. With Globus, subscribers can move, share, & discover data via a single interface – whether your files live on a supercomputer, lab clust
@broarr totally agree.  Also would it be possible to perhaps link to the Globus site in here somehow as this is the intro and directly have folks go to an intro video or something?

2020-05-11 14:18 UTC, hkershaw-brown commented
Who is the audience for this documentation?  

Why is globus in its gitbook?  I don't think this makes sense.  
Why is there only info for Linux Systems?

This documentation seems to mostly Amar's notes that came with his globus presentation way back when, so it does not seem ready for prime time.  Here are a few examples to illustrate this:

There are some super confusing parts for users:
"All users should have access to Research Folder on the //files.brown.edu/Research share. If you don’t have one, please open a Deskpro ticket using the appropriate snippet."

 - Are users supposed to get a deskpro agent account to use the appropriate snippet?

"This page will describe how to transfer local files on a Linux System to a Globus Endpoints. This utilizes the Globus Personal Endpoint client. Only user's home files can be transferred."
- what?

There is also none of the advice about how to use google drive with Globus (bundling transfers, coping with throttling, etc.)

The documentation is public already, so I am not sure what we are supposed to be reviewing in this commit? 

I think it would be better to plan what is going to do into this documentation first, before writing it.

2020-05-11 17:27 UTC, Kilatsat commented on content/english/services/infrastructure/globus.md
> +Globus is a secure, reliable research data management service. With Globus, subscribers can move, share, & discover data via a single interface – whether your files live on a supercomputer, lab clust
Link added and wording changed

2020-05-11 17:27 UTC, Kilatsat commented
I'm not sure all of this discussion is in-scope for this pull-request, to add a Globus section to the CCV website. 

I welcome any changes anyone would like to make directly on Gitbook!

2020-05-11 17:37 UTC, fernandogelin commented
@Kilatsat is right, the PR is just to add a Globus card to the website. But if the documentation has issues, that should be resolved before we can merge this.

@mttunca @paulstey thoughts?

2020-05-11 17:40 UTC, mttunca commented
Hi Fernando - Kirk is also working to resolve concerns with the
documentation. We'll have that addressed soon.

Best,
Mete


-----------------------------------------
Mete Tunca
Assistant Director, Cloud and Research Services
Brown University | Center for Computation and Visualization
(401) 863-7293 (office)
(401) 793-0067 (mobile)
http://www.ccv.brown.edu


On Mon, May 11, 2020 at 1:37 PM Fernando Gelin <notifications@github.com>
wrote:

> @Kilatsat <https://github.com/Kilatsat> is right, the PR is just to add a
> Globus card to the website. But if the documentation has issues, that
> should be resolved before we can merge this.
>
> @mttunca <https://github.com/mttunca> @paulstey
> <https://github.com/paulstey> thoughts?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/brown-ccv/ccv-website/pull/250#issuecomment-626847183>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKAFHRG7ZNLHU5QDM7YHSGDRRAZWBANCNFSM4MZ23VGA>
> .
>

2020-05-11 17:43 UTC, paulstey approved these changes

2020-05-11 17:43 UTC, paulstey commented on content/english/services/infrastructure/globus.md
> +Globus is a secure, reliable research data management service. With Globus, subscribers can move, share, & discover data via a single interface – whether your files live on a supercomputer, lab clust
I just have a couple of minor comments here:
    1. In the first sentence, we need a comma after the word `reliable`. 
    2. In the second sentence, we need to use the word `and`, rather than the `&`.
    3. In the second sentence, we ought to be using an em-dash, not an en-dash before `whether`. And there should not be spaces on either side of the en-dash.
    4. In the final sentence, the word `subscribers` should have an apostrophe after it to indicate the possessive.
    5. In the final sentence, we should replace `his/her` with the word `their`.

2020-05-11 17:51 UTC, broarr approved these changes

2020-05-11 19:08 UTC, Kilatsat commented on content/english/services/infrastructure/globus.md
> +Globus is a secure, reliable research data management service. With Globus, subscribers can move, share, & discover data via a single interface – whether your files live on a supercomputer, lab clust
all 5 changes are addressed in the most recent commit

2020-05-11 19:09 UTC, paulstey commented on content/english/services/infrastructure/globus.md
> +Globus is a secure, reliable research data management service. With Globus, subscribers can move, share, & discover data via a single interface – whether your files live on a supercomputer, lab clust
Awesome! Thanks, Kirk!

2020-05-11 19:15 UTC, broarr commented
Looks like his/her made it back into the globus document?

On Mon, May 11, 2020 at 3:09 PM Paul Stey <notifications@github.com> wrote:

> *@paulstey* commented on this pull request.
> ------------------------------
>
> In content/english/services/infrastructure/globus.md
> <https://github.com/brown-ccv/ccv-website/pull/250#discussion_r423258118>:
>
> > +title: Globus
>
> +
>
> +tagTitle: Globus
>
> +tagDescription: Transfer files asynchronously and securely
>
> +
>
> +date: 2020-05-05 18:29:17 +0000
>
> +category: File Storage and Transfer
>
> +icon: database
>
> +lead: Transfer files asynchronously and securely
>
> +weight: 0
>
> +docs_link: globus
>
> +
>
> +---
>
> +# Globus
>
> +
>
> +Globus is a secure, reliable research data management service. With Globus, subscribers can move, share, & discover data via a single interface – whether your files live on a supercomputer, lab cluster, tape archive, public cloud or your laptop, you can manage this data from anywhere via just a web browser and using your existing identities. Transfers are facilitated through endpoints. Endpoints are like collections pointing to subscribers specific datasets like his/her Google drive, research share or a folder on a computer.
>
>
> Awesome! Thanks, Kirk!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/brown-ccv/ccv-website/pull/250#discussion_r423258118>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALZRKTXC62NHQUFRNKEKWPDRRBEO7ANCNFSM4MZ23VGA>
> .
>

2020-05-11 19:17 UTC, broarr commented
Please disregard my previous email. The github emails made things look weird. Sorry!

2020-05-11 20:42 UTC, Kilatsat commented
Okay, all the specific Gitbook suggestions have been changed as well. Can this be merged now?

2020-05-12 02:25 UTC, mirestrepo commented
So everyone is aware, the Globus gitbook is synched to Brown's GitHub organization https://github.com/BrownUniversity/globus-documentation - I did that thinking that would be more accessible to other CIS teams (e.g) storage. Similarly to other documentation, I think GitHub is the best way to track issues on the contents of the Gitbook itself.

2020-05-12 14:30 UTC, paulstey approved these changes

2020-05-12 14:39 UTC, merged