feat: 🎸 Add commands to submit a PR
brown-ccv/ccv-website-hugo pull request #260
Opened 2020-05-14 22:22 UTC by yangliu2009

Add 'git checkout -b xxx', 'git add .' and 'git push' for submitting a
PR

### Pull Request
---

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [ ] Local site looks as expected after changes.
- [ ] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2020-05-18 13:16 UTC, fernandogelin requested changes

2020-05-18 13:16 UTC, fernandogelin commented on README.md
> +Once changes are done in your topic branch, use `git add .`, `npm run commit` and `git push` to submit a PR to `master` with the corresponding labels, and then a review is requested from up to 3 revi
@yangliu2009 these instructions are incorrect, `git push` doesn't submit a PR, it only pushes committed changes to the remote branch.

2020-05-19 16:25 UTC, yangliu2009 commented on README.md
> +Once changes are done in your topic branch, use `git add .`, `npm run commit` and `git push` to submit a PR to `master` with the corresponding labels, and then a review is requested from up to 3 revi
@fernandogelin  How about change 'submit a PR' to 'submit your changes'?

2020-05-19 16:36 UTC, fernandogelin commented on README.md
> +Once changes are done in your topic branch, use `git add .`, `npm run commit` and `git push` to submit a PR to `master` with the corresponding labels, and then a review is requested from up to 3 revi
@yangliu2009 it should be "... `git push -u origin your_topic_branch` to push your changes to the topic branch, then start a pull request from `your_topic_branch` to `master`"

2020-06-05 14:56 UTC, paulstey commented
@yangliu2009 and @mttunca 

Do we want to keep working on this PR? If so, could we please implement the corrections that @fernandogelin mentioned above?

Let me know if I can help! Thanks, guys!

Cheers,

Paul

2020-06-10 16:25 UTC, mcmcgrath13 requested changes

2020-06-10 16:25 UTC, mcmcgrath13 commented on README.md
> +To build the site into the `public/` folder. This generates all the files needed to publish the side, but doesn't start the server.
typo - rever to `site`

2020-06-10 16:25 UTC, mcmcgrath13 commented on README.md
> +The reviewer who merged the PR into `master` is responsible for starting a PR to `production` and assigning it to the `website-admin` team.
The wait times are still in play, but perhaps should be moved elsewhere because they are for merging into master not production.  Either way, I don't think this should be deleted at this time.

2020-06-10 16:25 UTC, mcmcgrath13 commented on README.md
> +Find detailed information on how to write your markdown content and include shortcodes specific for CCV's website [here](https://datasci.brown.edu/2019/02/how-to-write-docs-and-posts-for-the-ccv-webs
the old link seems to work while the new one doesn't - change back to old version

2020-06-10 16:25 UTC, mcmcgrath13 commented on README.md
> -- To add a new workshop/software to this list, add a file called `ready.yml` to **your workshop/software repository (not this repo!)**, follow example below.
@fernandogelin is this no longer the case?

2020-06-29 13:51 UTC, fernandogelin commented
closing as stale PR, feel free to reopen when requested changes are addressed.

2020-06-29 13:51 UTC, closed without merging