Feat storage
brown-ccv/ccv-website-hugo pull request #289
Opened 2020-06-23 14:32 UTC by fernandogelin

### Pull Request
---

#### PR Summary
Content for Storage Guide is now fetched from Deskpro RSS feed at build time. I would suggest also doing that for rates. It seems like that page gets updated a lot.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [x] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [x] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2020-06-23 14:57 UTC, paulstey approved these changes
Thank you, @fernandogelin!!!

2020-06-23 15:11 UTC, mttunca approved these changes

2020-06-23 15:16 UTC, mttunca commented
Thanks Fernando!

Best,
Mete

-----------------------------------------
Mete Tunca
Assistant Director, Cloud and Research Services
Brown University | Center for Computation and Visualization
(401) 863-7293 (office)
(401) 793-0067 (mobile)
http://www.ccv.brown.edu


On Tue, Jun 23, 2020 at 10:57 AM Paul Stey <notifications@github.com> wrote:

> *@paulstey* approved this pull request.
>
> Thank you, @fernandogelin <https://github.com/fernandogelin>!!!
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/brown-ccv/ccv-website/pull/289#pullrequestreview-435870956>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKAFHRHU56HMQUXG6NWOBRLRYC7HLANCNFSM4OFXHONQ>
> .
>

2020-06-23 15:54 UTC, mcmcgrath13 requested changes

2020-06-23 15:54 UTC, mcmcgrath13 commented on data/file_storage.yaml
> +    Click bellow to see detailed information and learn more about
typo, `bellow` -> `below`

2020-06-23 17:04 UTC, fernandogelin commented on data/file_storage.yaml
> +    Click bellow to see detailed information and learn more about
oops

2020-06-29 17:30 UTC, fernandogelin commented
Hi all, I made some major changes to include other articles from kb, so a full review is needed again.

2020-06-29 17:53 UTC, fernandogelin commented
https://review-app-feat-storage-x8s90w.herokuapp.com

2020-06-29 18:11 UTC, mcmcgrath13 commented
In the storage comparison table, it's unclear that the globus is covering three columns:
![image](https://user-images.githubusercontent.com/24885580/86040672-74cd2300-ba12-11ea-8b5a-ceb28e7350ac.png)

2020-06-29 18:14 UTC, mcmcgrath13 commented
This should say course or workshop: 
![image](https://user-images.githubusercontent.com/24885580/86040897-ce355200-ba12-11ea-915e-2dfe9270231d.png)

2020-06-29 18:15 UTC, mcmcgrath13 commented
![image](https://user-images.githubusercontent.com/24885580/86040970-f0c76b00-ba12-11ea-910b-46e3724c5e35.png)
link is missing

2020-06-29 18:20 UTC, mcmcgrath13 requested changes
It looks like there are images in some of these articles that aren't coming over (I see the sad image icon  here: 
![image](https://user-images.githubusercontent.com/24885580/86041377-8fec6280-ba13-11ea-852e-ecf446512468.png))
And also some of the links don't work: 
![image](https://user-images.githubusercontent.com/24885580/86041414-9aa6f780-ba13-11ea-9e6f-160254e1bcc1.png)
link is https://review-app-feat-storage-x8s90w.herokuapp.com/kb/articles/2

2020-06-29 18:20 UTC, mcmcgrath13 commented on content/english/services/infrastructure/storage.md
> +
this could use a table of contents or something - it's unclear that it's strung together articles, also some of the content overlaps

2020-06-29 18:34 UTC, fernandogelin commented
<img width="891" alt="Screen Shot 2020-06-29 at 2 34 16 PM" src="https://user-images.githubusercontent.com/3057156/86042771-a5fb2280-ba15-11ea-9999-1f1ae4b0b2d5.png">

Also, this should be fixed before we publish.

2020-06-29 18:38 UTC, fernandogelin commented
<img width="1052" alt="Screen Shot 2020-06-29 at 2 37 38 PM" src="https://user-images.githubusercontent.com/3057156/86043041-199d2f80-ba16-11ea-9e65-5af99542af1f.png">
I don't think we want this on the website..

2020-06-29 18:42 UTC, fernandogelin commented
> It looks like there are images in some of these articles that aren't coming over (I see the sad image icon here:
> ![image](https://user-images.githubusercontent.com/24885580/86041377-8fec6280-ba13-11ea-852e-ecf446512468.png))
> And also some of the links don't work:
> ![image](https://user-images.githubusercontent.com/24885580/86041414-9aa6f780-ba13-11ea-9e6f-160254e1bcc1.png)
> link is https://review-app-feat-storage-x8s90w.herokuapp.com/kb/articles/2

Even if the image had loaded, it looks like super outdated:
<img width="366" alt="Screen Shot 2020-06-29 at 2 41 10 PM" src="https://user-images.githubusercontent.com/3057156/86043391-ae079200-ba16-11ea-9b5a-586bd0757587.png">

that's not what I see when I go to webfiles.brown.edu

2020-06-29 19:06 UTC, fernandogelin commented
<img width="1186" alt="Screen Shot 2020-06-29 at 3 05 56 PM" src="https://user-images.githubusercontent.com/3057156/86045806-1c018880-ba1a-11ea-8528-22ac84d0a846.png">

Also, should these cards be removed?

2020-07-15 13:24 UTC, mcmcgrath13 commented
The links in the table go back to kb instead of the in-document links - is that intentional? @fernandogelin @singhsaluja 

The globus link there also goes to a google doc -should it go to the globus docs on gitbook?

2020-07-15 15:14 UTC, mirestrepo commented
I have (hopefully) corrected the typos on the JupyterHub on the KB article. I'll leave the rebuilding of the docker image at your convenience in case you want to wait for the storage changes. I'll maybe email Storage team to make the changes on the storage side

2020-07-15 15:25 UTC, mirestrepo commented on content/english/services/infrastructure/storage.md
> +
Is this still relevant? I don't see the restore Files section anywhere

2020-07-15 15:26 UTC, mirestrepo commented
> > It looks like there are images in some of these articles that aren't coming over (I see the sad image icon here:
> > ![image](https://user-images.githubusercontent.com/24885580/86041377-8fec6280-ba13-11ea-852e-ecf446512468.png))
> > And also some of the links don't work:
> > ![image](https://user-images.githubusercontent.com/24885580/86041414-9aa6f780-ba13-11ea-9e6f-160254e1bcc1.png)
> > link is https://review-app-feat-storage-x8s90w.herokuapp.com/kb/articles/2
> 
> Even if the image had loaded, it looks like super outdated:
> <img alt="Screen Shot 2020-06-29 at 2 41 10 PM" width="366" src="https://user-images.githubusercontent.com/3057156/86043391-ae079200-ba16-11ea-9b5a-586bd0757587.png">
> 
> that's not what I see when I go to webfiles.brown.edu

I don't see this in the KB article....

2020-07-15 15:54 UTC, mirestrepo commented
> In the storage comparison table, it's unclear that the globus is covering three columns:
> ![image](https://user-images.githubusercontent.com/24885580/86040672-74cd2300-ba12-11ea-8b5a-ceb28e7350ac.png)

I asked storage team and this is the response:
"We had that originally and feedback from others thought it was too busy.  We could remove the logo and use text if the logo is causing problems with the RSS feed to CCV"

Do we prefer with no logo?

2020-07-16 18:21 UTC, fernandogelin commented
> > In the storage comparison table, it's unclear that the globus is covering three columns:
> > ![image](https://user-images.githubusercontent.com/24885580/86040672-74cd2300-ba12-11ea-8b5a-ceb28e7350ac.png)
> 
> I asked storage team and this is the response:
> "We had that originally and feedback from others thought it was too busy. We could remove the logo and use text if the logo is causing problems with the RSS feed to CCV"
> 
> Do we prefer with no logo?

@mirestrepo I think no logo is probably better.. it's also linking to a google doc which is not ideal..

2020-07-21 14:37 UTC, fernandogelin commented
> The links in the table go back to kb instead of the in-document links - is that intentional? @fernandogelin @singhsaluja
> 
> The globus link there also goes to a google doc -should it go to the globus docs on gitbook?

@mttunca @singhsaluja @paulstey Can someone look into this?

2020-07-21 15:17 UTC, paulstey commented
Yes, the Globus link should go to GitBook. We're not going to maintain the docs in two places.

2020-07-21 15:26 UTC, paulstey approved these changes

2020-07-21 15:33 UTC, merged

2020-07-21 17:59 UTC, mirestrepo commented
> > The links in the table go back to kb instead of the in-document links - is that intentional? @fernandogelin @singhsaluja
> > The globus link there also goes to a google doc -should it go to the globus docs on gitbook?
> 
> @mttunca @singhsaluja @paulstey Can someone look into this?

I have pinged storage team in their [google doc](https://docs.google.com/document/d/1mk5HDFyvUe7Zd7ww5f9wPht7VCxCOso2dnVHzmto8gE/edit?disco=AAAAJ0zpJGQ) hopefully remove logo and change link url