feat: add condo puchase card in services
brown-ccv/ccv-website-hugo pull request #292
Opened 2020-06-24 19:29 UTC by paulstey

### Pull Request
Add card describing condo purchase

#### PR Summary
This PR adds a card to the `Services` section regarding the purchasing of HPC condos

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [ ] Local site looks as expected after changes.
- [ ] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2020-06-24 19:29 UTC, paulstey commented
This closes #133

2020-06-24 19:34 UTC, fernandogelin approved these changes
Looks great!

2020-06-24 19:36 UTC, mcmcgrath13 requested changes

2020-06-24 19:36 UTC, mcmcgrath13 commented on content/english/services/infrastructure/hpc-condo.md
> +CCV standardizes processor, and to an extent, node memory configurations for a period of roughly six months to a year in order to maintain a degree of homogeneity in the cluster. As an example, our c
should be `processors`

2020-06-24 19:36 UTC, mcmcgrath13 commented on content/english/services/infrastructure/hpc-condo.md
> +CCV standardizes processor, and to an extent, node memory configurations for a period of roughly six months to a year in order to maintain a degree of homogeneity in the cluster. As an example, our c
what do the processors have to do with job priority?

2020-06-24 19:40 UTC, mcmcgrath13 commented on content/english/services/infrastructure/hpc-condo.md
> +lead: Dedicated high-performance computing resources for researchers in the form of "condos" on the University's main supercomputer (i.e., "Oscar").
instead of `supercomuter (i.e., "Oscar")` I'd do just `supercomputer, Oscar` and maybe link to the page on oscar.  
It seems weird that this card shows up first in the list on computing, if the `weight` is changed one way or another does that push it further down?

2020-06-24 19:40 UTC, paulstey commented on content/english/services/infrastructure/hpc-condo.md
> +CCV standardizes processor, and to an extent, node memory configurations for a period of roughly six months to a year in order to maintain a degree of homogeneity in the cluster. As an example, our c
Fixed!

2020-06-24 19:42 UTC, mcmcgrath13 requested changes

2020-06-24 19:42 UTC, mcmcgrath13 commented on content/english/services/infrastructure/hpc-condo.md
> +CCV standardizes processor, and to an extent, node memory configurations for a period of roughly six months to a year in order to maintain a degree of homogeneity in the cluster. As an example, our c
the `, and to an extent,` between processor and node memory configurations makes the intent unclear.  are processors standardized? or processor configurations? I would simplify this sentence a bit

2020-06-24 19:47 UTC, paulstey commented on content/english/services/infrastructure/hpc-condo.md
> +lead: Dedicated high-performance computing resources for researchers in the form of "condos" on the University's main supercomputer (i.e., "Oscar").
Fixed!

2020-06-24 19:51 UTC, paulstey commented on content/english/services/infrastructure/hpc-condo.md
> +CCV standardizes processor, and to an extent, node memory configurations for a period of roughly six months to a year in order to maintain a degree of homogeneity in the cluster. As an example, our c
Fixed!

2020-06-24 20:00 UTC, mcmcgrath13 approved these changes

2020-06-25 12:33 UTC, mttunca approved these changes

2020-06-29 13:59 UTC, merged