feat: 🎸 Add details for RData
brown-ccv/ccv-website-hugo pull request #328
Opened 2020-10-17 01:42 UTC by yangliu2009

Added Location, Rates, Access and Transfer for RData

### Pull Request
---

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [x ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x ] Commitizen was used for all commits.
- [x ] Local site looks as expected after changes.
- [ x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2020-10-17 18:18 UTC, paulstey commented
This looks great; thank you, @yangliu2009!!!

2020-10-17 18:18 UTC, paulstey approved these changes

2020-10-19 16:42 UTC, mirestrepo requested changes

2020-10-19 16:42 UTC, mirestrepo commented on content/english/services/infrastructure/rdata.md
> +* Users can [transfer data between their local computers and Rdata](https://docs.ccv.brown.edu/oscar/managing-files/filetransfer-isilon)
I think the link should be https://docs.ccv.brown.edu/oscar/managing-files/filetransfer

2020-10-19 18:31 UTC, yangliu2009 commented on content/english/services/infrastructure/rdata.md
> +* Users can [transfer data between their local computers and Rdata](https://docs.ccv.brown.edu/oscar/managing-files/filetransfer-isilon)
nice catch, Isabel. The link is corrected now. Thanks.

2020-10-20 18:08 UTC, mcmcgrath13 commented
@yangliu2009 I changed the pr type to `content` as this just touches the content folder - less review needed 😉

2020-10-20 18:10 UTC, mcmcgrath13 approved these changes

2020-10-20 18:10 UTC, merged