feat: 🎸 Updated the link for Storage Guide in the Services page
brown-ccv/ccv-website-hugo pull request #336
Opened 2020-11-18 16:02 UTC by yangliu2009

Updated the link to
https://ithelp.brown.edu/kb/articles/decide-how-to-store-and-share-files-for-researchers
for Storage Guide

### Pull Request
---

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [x ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ x] Commitizen was used for all commits.
- [x ] Local site looks as expected after changes.
- [ x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2020-11-23 20:02 UTC, yangliu2009 commented
@fernandogelin @mirestrepo - Is there anything needed from me for the pull request? Thanks.

2020-11-23 20:07 UTC, mirestrepo commented
The link looks good to me, @fernandogelin should @yangliu2009 also remove [this page](https://github.com/brown-ccv/ccv-website/blob/master/content/english/services/infrastructure/storage.md)

2020-11-23 20:09 UTC, fernandogelin requested changes

2020-11-23 20:09 UTC, fernandogelin commented on themes/gb-theme/layouts/_default/list.html
> +                <a class="fs-26" href="https://ithelp.brown.edu/kb/articles/decide-how-to-store-and-share-files-for-researchers">
we should keep the path in the markdown file, just change this line to: `<a class="fs-26" href="{{.Site.Data.file_storage.path}}">`
and update the `path` in the `data/file_storage.yaml`

2020-11-23 20:13 UTC, fernandogelin commented
> The link looks good to me, @fernandogelin should @yangliu2009 also remove [this page](https://github.com/brown-ccv/ccv-website/blob/master/content/english/services/infrastructure/storage.md)? And are there more hidden related content?

yes, I think that page can be removed.

2020-11-24 13:18 UTC, yangliu2009 commented
@fernandogelin @mirestrepo - Made changes as requested except that {{.Site.BaseURL}}/ is not added, since it resulted in 404 on my local computer.

2020-12-01 21:12 UTC, yangliu2009 commented
@fernandogelin @mirestrepo - Can the pull request be approved? Thanks.

Yang

2020-12-01 21:18 UTC, fernandogelin approved these changes

2020-12-02 17:44 UTC, paulstey approved these changes

2020-12-15 21:20 UTC, merged