Content terms and risk
brown-ccv/ccv-website-hugo pull request #341
Opened 2020-12-15 15:21 UTC by AlexDuchnowski

### Pull Request
---

#### PR Summary
The addition of the Terms of Service for the Oscar details page, the addition of data risk levels for 'Computing' Services, and new icons for the About page

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [x] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2020-12-15 15:39 UTC, mcmcgrath13 requested changes
🚀 I still need to look at the changes in the browser, but my computer decided I needed to reinstall a bunch of software first...

2020-12-15 15:39 UTC, mcmcgrath13 commented on content/english/services/_index.md
> +    text: See our Rates
why capitalize rates?

2020-12-15 15:39 UTC, mcmcgrath13 commented on content/english/services/infrastructure/hpc-condo.md
> +
remove empty lines

2020-12-15 15:39 UTC, mcmcgrath13 commented on themes/gb-theme/layouts/about/.vs/VSWorkspaceState.json
> +{
are these files added by your IDE? If so, add them to the gitignore and delete them from the PR

2020-12-15 15:40 UTC, fernandogelin commented
Link to the deployment of this PR: https://review-app-content-term-k09f0u.herokuapp.com

2020-12-15 15:47 UTC, AlexDuchnowski commented on content/english/services/_index.md
> +    text: See our Rates
Not sure... I'll change it back.

2020-12-15 15:50 UTC, AlexDuchnowski commented on themes/gb-theme/layouts/about/.vs/VSWorkspaceState.json
> +{
Yep, Visual Studios added those. How do I add them to the gitignore and delete them from the PR?

2020-12-15 15:51 UTC, mcmcgrath13 commented
Some more thoughts from reviewing in the browser:

* Why only have the risk classification on compute - isn't that more of a storage thing?
  * with the risk classification on all of those, the styling feels a bit agressive -  maybe make it a bit more subtle/friendly?
* In the terms of service the ccv rates link is hard coded, should be relative
* I prefer the crow logo for the mission in about

2020-12-15 15:54 UTC, mcmcgrath13 commented on themes/gb-theme/layouts/about/.vs/VSWorkspaceState.json
> +{
add a glob that matches them in `.gitignore` (https://blog.martinhujer.cz/dont-put-idea-vscode-directories-to-projects-gitignore/)

and then https://devconnected.com/how-to-delete-file-on-git/#:~:text=The%20easiest%20way%20to%20delete,the%20file%20to%20be%20deleted.&text=Note%20that%20by%20using%20the,be%20deleted%20from%20the%20filesystem. for removing the files

2020-12-16 21:40 UTC, AlexDuchnowski commented on themes/gb-theme/layouts/about/.vs/VSWorkspaceState.json
> +{
I just tried adding the glob, removing the files, committing, and then pushing, but I can't tell if it worked. Did it?

2020-12-16 22:01 UTC, AlexDuchnowski commented on themes/gb-theme/layouts/about/.vs/VSWorkspaceState.json
> +{
I tried one more time, and I think it has worked. Please let me know if it hasn't. Thanks!

2020-12-16 22:29 UTC, mcmcgrath13 commented on themes/gb-theme/layouts/about/.vs/VSWorkspaceState.json
> +{
looks good to me!

2020-12-17 14:02 UTC, AlexDuchnowski commented
@mcmcgrath13 

> Some more thoughts from reviewing in the browser:
> 
> * Why only have the risk classification on compute - isn't that more of a storage thing?
>   
>   * with the risk classification on all of those, the styling feels a bit agressive -  maybe make it a bit more subtle/friendly?
> * In the terms of service the ccv rates link is hard coded, should be relative
> * I prefer the crow logo for the mission in about

I've changed the rates link.

I'd like to try changing the color scheme for the data risk classification labels/buttons, but I'm having trouble finding the right file to edit (I'll ask around on Slack).

I'm happy to change the mission icon back to the crow, but I was thinking that it would make more sense to have an icon that is somehow related to the concept of a mission statement.

Here are a few alternatives:
- [Road](https://fontawesome.com/icons/road?style=solid)
- [Globe-americas](https://fontawesome.com/icons/globe-americas?style=solid)
- [Globe](https://fontawesome.com/icons/globe?style=solid)
- [Location-arrow](https://fontawesome.com/icons/location-arrow?style=solid)

If you don't think any of these are better, I'll change it back right away. Thanks for all the feedback!

2020-12-17 18:07 UTC, AlexDuchnowski commented
The pull request is ready for re-review now.

2020-12-17 20:06 UTC, mcmcgrath13 approved these changes
🚀

2021-01-05 13:41 UTC, AlexDuchnowski commented
@paulstey @mttunca - Happy New Year! Is there anything you would like me to change here, or can this request be merged now?

Thanks in advance,

Alex

2021-01-05 14:55 UTC, paulstey approved these changes

2021-01-05 14:56 UTC, merged