feat: add link to status page in quick links
brown-ccv/ccv-website-hugo pull request #359
Opened 2021-02-10 19:59 UTC by paulstey

This PR add a link to the CCV Status app on to our front page in the `Quick Links` section.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [ ] Local site looks as expected after changes.
- [ ] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2021-02-10 20:32 UTC, mcmcgrath13 requested changes
delete the .DS_Store file and gitignore it

2021-02-10 20:32 UTC, mcmcgrath13 commented on content/english/_index.md
> +    href: "https://status.ccv.brown.edu"
why do the above have weights and this one doesn't?

2021-02-10 20:33 UTC, mcmcgrath13 commented
:rocket:

I don't love that on a typical browser width the cards are different heights:
![image](https://user-images.githubusercontent.com/24885580/107568608-4113c780-6bb5-11eb-902c-0784712a4b3c.png)

Could we either 1) enforce the card heights to be even or 2) make the content lengths more similar so that they functionally have the same height for typical browser widths?

2021-02-10 20:41 UTC, mcmcgrath13 commented
![image](https://user-images.githubusercontent.com/24885580/107569384-3e65a200-6bb6-11eb-805f-128b2f44e09e.png)
This is with adding `align-items: stretch` to `.row` and `height: 100%` to `.scale`.  I'm not sure if these classes are used elsewhere, so that should be assessed before applying (and or narrowing the selection rules, so they only apply here).

2021-02-10 21:56 UTC, paulstey commented on content/english/_index.md
> +    href: "https://status.ccv.brown.edu"
Good catch, @mcmcgrath13!! This is fixed in the newest commit!

2021-02-10 21:57 UTC, paulstey commented
Thanks, @mcmcgrath13!! The card heights should now be fixed, too!

2021-02-10 22:32 UTC, mcmcgrath13 approved these changes

2021-02-11 20:00 UTC, singhsaluja approved these changes

2021-02-11 20:50 UTC, merged