feat: 🎸 Cloud Computing Page
brown-ccv/ccv-website-hugo pull request #367
Opened 2021-02-19 18:58 UTC by AlexDuchnowski

Creation of new cloud computing page explaining CCV connections to AWS
and GCP resources

### Pull Request
---

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [x] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [x] Commitizen was used for all commits.
- [x] Local site looks as expected after changes.
- [x] Contributing guidelines were followed.
- [x] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2021-02-22 13:43 UTC, mcmcgrath13 requested changes

2021-02-22 13:43 UTC, mcmcgrath13 commented on content/english/services/infrastructure/cloud-computing.md
> +  text: "Risk Classification: N/A (Not owned by Brown University)"
does this mean any usage of these services needs to reviewed by security? if you have risk category 2 data, can you use it here?

2021-02-22 13:43 UTC, mcmcgrath13 commented on content/english/services/infrastructure/cloud-computing.md
> +  text: "Risk Classification: N/A (Not owned by Brown University)"
@mttunca

2021-02-22 13:43 UTC, mcmcgrath13 commented on content/english/services/infrastructure/cloud-computing.md
> +For more information about Machine Learning with AWS, go [here](https://aws.amazon.com/machine-learning/).
A `here` link is not very accessible as it doesn't tell someone using a screen reader where they are going.  Could you make that more descriptive.  Maybe something like `Go to [AWS Machine Learning] for more information.`?

2021-02-22 13:43 UTC, mcmcgrath13 commented on content/english/services/infrastructure/cloud-computing.md
> +# Google Cloud Platform
What about general use of GCP for research?  Is there a process for requesting a project or management of a billing account you can use?  I know this is currently a pain point that I believe @mttunca had said was being worked on.

2021-02-22 18:54 UTC, AlexDuchnowski commented on content/english/services/infrastructure/cloud-computing.md
> +For more information about Machine Learning with AWS, go [here](https://aws.amazon.com/machine-learning/).
I just changed the link name. Is it good now?

2021-02-22 19:04 UTC, AlexDuchnowski commented
@mcmcgrath13 By the way, more information on cloud computing is being collected, so please don't merge the PR yet (even if the conversations about it so far have been resolved). Thanks.

2021-02-22 19:27 UTC, mcmcgrath13 commented on content/english/services/infrastructure/cloud-computing.md
> +For more information about Machine Learning with AWS, go [here](https://aws.amazon.com/machine-learning/).
looks great! thanks!

2021-02-25 16:17 UTC, yangliu2009 commented
Closing the pull request for now, as there are discussions ongoing for this.

2021-02-25 16:17 UTC, closed without merging