feat: 🎸 add two new cards to whatsnew
brown-ccv/ccv-website-hugo pull request #386
Opened 2021-04-29 21:19 UTC by paulstey

BREAKING CHANGE: 🧨 no

This PR just refreshes the `What's New` section with a couple of new cards. 

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [ ] Local site looks as expected after changes.
- [ ] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2021-04-29 21:29 UTC, singhsaluja approved these changes

2021-05-06 19:28 UTC, mcmcgrath13 requested changes

2021-05-06 19:28 UTC, mcmcgrath13 commented on data/whatsnew.yaml
> +    text: CCV will be hosting an introductory Python workshop. [**Check out Python workshop details.**](https://today.brown.edu/events/139280?utm_source=todayAtBrown&utm_medium=email&utm_campaign=Cam
we probably don't want those utm sources in the url, right?

2021-05-06 19:28 UTC, mcmcgrath13 commented on data/whatsnew.yaml
> +    text: There is a new Research Compute tab on the myBrown portal! [**Check out the myBrown Portal!**](https://my.brown.edu/web/guest/research-compute)
does everyone have the research compute tab? if not, what happens if they follow this link and they don't?

2021-05-06 19:29 UTC, paulstey commented on data/whatsnew.yaml
> +    text: There is a new Research Compute tab on the myBrown portal! [**Check out the myBrown Portal!**](https://my.brown.edu/web/guest/research-compute)
Thanks for checking, @mcmcgrath13! And yes, everyone should be able to see that tab. Do you not see it?

2021-05-06 21:28 UTC, paulstey commented on data/whatsnew.yaml
> +    text: CCV will be hosting an introductory Python workshop. [**Check out Python workshop details.**](https://today.brown.edu/events/139280?utm_source=todayAtBrown&utm_medium=email&utm_campaign=Cam
Fixed! Thank you, @mcmcgrath13!!

2021-05-06 21:56 UTC, mcmcgrath13 commented on data/whatsnew.yaml
> +    text: There is a new Research Compute tab on the myBrown portal! [**Check out the myBrown Portal!**](https://my.brown.edu/web/guest/research-compute)
I did! But I didn't know if all would (undergrads, e.g.)

2021-05-06 21:56 UTC, mcmcgrath13 approved these changes

2021-05-06 22:07 UTC, paulstey commented
Thank you, @mcmcgrath13 and @singhsaluja!!!

2021-05-06 22:07 UTC, merged