add oit links
brown-ccv/ccv-website-hugo pull request #397
Opened 2021-06-30 15:19 UTC by paulstey

This PR adds a few links to OIT main page; this is to address comments from OIT directors. This PR also includes a bit of content update to the lead on the `About` page.

#### PR Summary
Briefly describe the changes.

#### Check the types of changes present in this PR:
- [ ] :bug: Bug
- [ ] :dragon: Feature
- [ ] :frog: Data (data folder - people/opportunities)
- [ ] :dog: Content (content folder)
- [ ] :blowfish: Other. Specify:

#### Checklist:
- [ ] Commitizen was used for all commits.
- [ ] Local site looks as expected after changes.
- [ ] Contributing guidelines were followed.
- [ ] If changes affect development, was the README updated?

##### If PR to `production`
- [ ] Development site (https://datasci.brown.edu) was checked and looks as expected.

2021-06-30 15:28 UTC, mcmcgrath13 requested changes

2021-06-30 15:28 UTC, mcmcgrath13 commented on content/english/about/_index.md
> +    Information technology (OIT)](https://it.brown.edu). CCV provides research computing
```suggestion
    Information Technology (OIT)](https://it.brown.edu). CCV provides research computing 
```

2021-06-30 15:28 UTC, mcmcgrath13 commented on content/english/services/_index.md
> +  lead: 'CCV provides computing infrastructure, consulting, and support to the Brown Community. We
what happened to the formatting here? did any content change?

2021-06-30 15:30 UTC, paulstey commented on content/english/about/_index.md
> +    Information technology (OIT)](https://it.brown.edu). CCV provides research computing
Good catch! Thank you, Mary!

2021-06-30 15:31 UTC, paulstey commented on content/english/services/_index.md
> +  lead: 'CCV provides computing infrastructure, consulting, and support to the Brown Community. We
Good question! I'm not sure, I think I tweaked some indents. There is no content change.

2021-06-30 16:54 UTC, mcmcgrath13 approved these changes

2021-07-19 15:52 UTC, singhsaluja approved these changes

2021-07-19 15:54 UTC, merged